repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.20.1
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear==20.1.4
